[package]
name = "chip8ulator"
version = "0.1.0"
authors = ["Roger Andersen <hexjelly@hexjelly.com>"]

[lib]
name = "chip8ulator"

[dependencies]
byteorder = "1.2.1"
minifb = "0.10.4"
failure = "0.1.1"
log = "0.4.1"
simplelog = "^0.5.1"
structopt = "0.2"
rand = "0.5.0"
